### PR TITLE
Update to 1.18.x, 1.19.x

### PR DESCRIPTION
**Pull request by MeeniMc**

### CODE REVIEW

**Comment by VatraXD** [comment]
Did you even try this? Simply not working.

**Comment by MeeniMc** [comment]
I have tested it, in fact I am using it everyday. Sorry it didn't work for you, but maybe if you would give less attitude and more details you'd receive more helpful feedback.

**Comment by MeeniMc** [comment]
works with 1.18.2 with no changes.

**Comment by VatraXD** [comment]
sorry for smack talking before, but it still doesn't work in 1.18, neither in survival or multiplayer, not with newer fabric, not with older.
ideas?

https://streamable.com/a7eonh

**Comment by MeeniMc** [comment]
works with 1.19pre4 without changes (beside gradle and version lock)

**Comment by MeeniMc** [comment]
Published a compiled version if anybody needs that
https://github.com/MeeniMc/Automatic-Elytra/releases

**Comment by MeeniMc** [comment]
works with 1.19.3 with no changes

**Comment by sternschnaube** [comment]
Hello @MeeniMc, thank you for mainting and confirming the 1.19.3 compatibility.
Much love 😊

**Comment by MeeniMc** [comment]
Works with 1.19.4 with no changes

**Comment by MeeniMc** [comment]
Mod is abandoned; I am now using https://modrinth.com/mod/jjelytraswap

**Pull request closed without merging**
